content/chunk24/Fix_ShoppingBag_C_00_02_RoomEntityParent.entity.patch.json

Reparents ShoppingBag_C_00_02 to the proper room entity so it's no longer invisible in 47's suite

feat: fix ShoppingBag_C_00_02's parent room entity (closes #2)

---

manifest.json

Fixes #16
Civilian in Berlin by the projection bar has an invisible torso mesh. It is in the deletion lists of chunk0patch4, chunk2patch3 and chunk4patch2. It is deleted from all chunks where it's supposed to exist. This will pull it to the chunk0 patch SMF creates.

fix: Restore deleted tracksuit top mesh

---

manifest.json

feat: new descriptions for three items: the Shears and Branson MD-2 Microphone, while the Burial Dagger gets a new name and description; Janus' Burial Dagger. the name is specifically a toggleable option that can be disabled. 
these changes are a part of Update 1.2.47 of [The Great Big Localisation Revamp](https://www.nexusmods.com/hitman3/mods/549) already, these have been backported here with the changes largely intact.

feat: edited descriptions for the Shears, Ceremonial Dagger and renamed Purple Duck Option

---

COPYING
COPYING.GPL
IOblobs/placeholder.txt
blobsIOI/placeholder.txt
manifest.json

This will update the license (and, to a lesser extent, the folder structure) to make it more clear what's the property of IO and what was made or edited by this mod's contributors.
Related to #102, which was supposed to be a quick, easy fix... it was not :p

chore: update license to exclude IOI assets

---

content/SmallFixes/chunk10/WaterScooterFix/setpiece_opulent_trap_waterscooter_a.entity.patch.json

In the unmodded game, oil puddles don't appear properly under sabotaged water scooters. This fixes that.
Made by Cybore on Discord, I'm just making the PR.

feat: make oil puddles appear properly for HAVEN water scooters

---

manifest.json

Somehow, Luiluix has gone uncredited for a while. That's not right!

fix: update manifest.json to properly include Luiluix

---

content/SmallFixes/chunk6/RatAgility/scenario_rat.entity.patch.json

Fixes these 2 coverplanes that clip into props on the sniper building rooftop in Chongqing:

feat: fix 2 coverplanes on sniper building rooftop in Chongqing

---

manifest.json

This should solve a load order conflict, hopefully.

fix: change manifest to load before Freelancer Variations

---

content/SmallFixes/chunk0/FreelancerDubaiEscapeFix/mission_hot_chess.entity.patch.json

This was made by team ruddcy.
In vanilla, about 50% of leaders will fail to evacuate due to a bug. Instead, they'll just stand there panicking and trying to evacuate, but they can't because their exit is broken.

feat: fix Dubai exits for Freelancer Leaders being broken when trying to evacuate during Showdowns

---

content/SmallFixes/chunk27/CanopyLOD/Canopy_Shop_B_Up_4m_00_02.entity.patch.json

Adds a LOD property used by other canopies on other backdrop buildings so that the model does not disappear when viewed from within the level boundaries

feat: add LOD property to canopy from backdrop building H

---

content/SmallFixes/chunk29/SeparateBedroomAndHallwayPaintings/bedroom_hatch_painting_id.entity.patch.json

Gives unique IDs to the bedroom hatch painting so it no longer shares IDs with the ground floor hallway painting.

feat: separate hallway and bedroom paintings, fixes #136

---

content/SmallFixes/chunk0/AmbroseAccessCardMapLabels/dugong_mcguffinkey_a.entity.patch.json
content/SmallFixes/chunk0/AmbroseAccessCardMapLabels/dugong_mcguffinkey_b.entity.patch.json

The cards were incorrectly labeled "Backup Data Disk" on the map. They are now correctly labeled Control Unit Access Card A and Control Unit Access Card B.

feat: rename Ambrose Control Unit Access Card map labels

---

content/SmallFixes/chunk1/lamp_spot_light_c.entity.patch.json

Added a missing event to control the lamp glowing when on/off
This is how it looks in vanillla:
This is how it looks with the fix:

feat: fix lamp_spot_light glowing when off

---

content/SmallFixes/chunk25/ActorSwapping/npc_mission_spider.entity.patch.json

Inverses the actors during the dialogue between the printing crew to reflect their actions in the game
(Thanks Sinful Monsoon on Discord for reporting it)

feat: swap dialogue to match actions

---

manifest.json

DIF (Disguise Inconsistencies Fixes) isn't listed in the manifest so I added it. Also alphabetised both the credits and the options as some general cleanliness.

feat: update manifest.json to list the Disguise Inconsistencies Fixes folder

---

content/SmallFixes/chunk25/RiotSmokeGrenadesSoundFix/smoke_grenade_a.entity.patch.json
content/SmallFixes/chunk8/RiotFlaresSoundFix/flare_a.entity.patch.json

Moves the sound of the flares to origin to match the actual position of the item and adds missing valuebool connection to the smoke grenades

feat: fix flares and smoke grenades not being audible

---

content/SmallFixes/chunk16/WhittletonCourierVoice/SolitaireCourierVoice.entity.patch.json

fixes #216 
Tested in-game, seems to work - courier speaks with the expected voice type and moves on with his routine as he's meant to.

feat: correct a Freelancer courier's voice in Whittleton Creek

---

content/SmallFixes/chunk19/FireAlarmClipping/location.entity.patch.json

moves the fire alarm slightly forward to prevent clipping with wall decal creating a yellow square on the model when viewed from far away

feat: fix fire alarm clipping in Kowoon Paddock

---

content/SmallFixes/chunk0/RFIDCrowdFix/prophelper_ica_trigger_proximity.entity.patch.json

In the base game, the RFID proximity explosive explodes from proximity to a crowd. This patch fixes it to only detonate with the coin present.

feat: fix RFID explosive triggering on crowds

---

content/OutfitFilterFixes/chunk18/WrongFiltersRemovedColombia.entity.patch.json

At least I sure hope this is all of them!
This time I searched for voice filters and removed them from everyone who had nothing covering their mouth.
This also removes some collateral transforms that apparently slipped into the previous version of the patch.
fixes #233

fix: remove ALL incorrect voice filters from Colombia

---

manifest.json

- make a toggle to replace French and German localisations for the unlockable Super Fan name with the original localisations from the Super Fan disguise
- remove "Rename Purple Streak Duck" toggle due to IOI's renaming
- move localisations for "Snow Globe" spelling to a toggle
- correct spelling of Splitter VHS to "Good Quack Vol. 3" VHS Tape
- change syntax of a conditional option

enhancement: toggles for Super Fan, Snow Globes, and more

---

content/SmallFixes/chunk19/BoatshopPinboard/location.entity.patch.json

Changes some unused pins on the pinboard to be invisible so that they don't float in the air (there's actually just one that's visible the others are in the walls)

feat: make floating pins from pinboard invisible

---

content/SmallFixes/chunk24/TagCorrections/009176DD8FB368C8.dlge.json

Previously used `In-world_PA_Processed_Volumetric` which is a loud, echo-y speaker sound even though she's sitting on a chair in a quiet basement talking to the security guard right next to her.
Now uses `In-world_Mission_UnImportant` to match the rest of the conversation.

feat: correct soundtag for dr4308_hotelstaffadmirecrew_civfem01_006

---

content/SmallFixes/chunk6/SplitterShootingRangeKillBox/shootingrange.entity.patch.json

The range's kill box volume no longer extends beyond the firing line.

feat: adjust The Splitter shooting range's kill box (fix #263 by Cybore)

---

content/SecurityCams/chunk17/mumbaihardcam.entity.patch.json

enables recording for slum cams added in master difficulty.

feat: Mumbai Master difficulty slum cams not hooked up to a recorder

---

content/SmallFixes/chunk0/GraduationRookPosition/fix_rook_ending_position.entity.patch.json
content/SmallFixes/chunk0/GraduationRookPosition/fix_rook_starting_position.entity.patch.json

Fixes #318
Needs a little bit of testing, I've made sure it doesn't erroneously return to the ending position on start and save/load. I don't think there's another way it could reset back to there.

feat: fix rook positioning in The Final Test

---

manifest.json

- see #180 for even more details
- remove officially fixed English localisation for `CHALLENGEPACK_ARGENTUM_WOLVERINEFINISHER_DESC`
- add translations for "Good Quack Vol. 3" VHS Tape
- change "chuck full" to "chock full" in the VHS description
- fix capitalization of "ICA Delegation" starting location
- change "imbedded" to "embedded" in ICA Delegation description
- change The Splitter's cloning tanks picture-in-picture's generic "Boil" text to "Boiling Point Reached" with translations
- change "A Matter of Loyalty" challenge description to `<li>[REDACTED]</li>` to match other redacted challenges
- add many Spanish localisation changes based on ones provided by IWILLCRAFT
- change more Spanish localisations from "Hawke's Bay" to "Bahía de Hawke"
- sort manifest localisationOverrides …

feat: fix numerous typos and improve translations

---

content/SmallFixes/chunk29/BerlinAndDubaiChopperSounds/vehicle_exit_sound_fixes.entity.patch.json

- fixes #137
- black & gold helicopter from Dubai now has sound when leaving the safehouse
- motorcycle from Berlin now uses the same sound as the Dartmoor motorcycle when leaving the safehouse

feat: fix Safehouse exit audio for Berlin + Dubai choppers

---

manifest.json

This name is used in all non-English languages (except xx and, obviously, non-Latin script). It's a bit weird to call him by his middle name in this one context only.

feat: correct phone in Zaydan's office from "Call Hugo Strandberg" to "Call Claus Hugo Strandberg" & update credits in manifest

---

content/SmallFixes/chunk24/TagCorrections/00BE4F0B36B79356.dlge.json

Was `In-world_Telephoneprocessed`, is now `In-world_Mission_Normal` to match the rest of the conversation
Located in Bangkok, on the porch above the docks loading area.

feat: correct soundtag on dr4238_gueststalksanguine_civmale01_006

---

content/DIF/chunk9/Miami/RaceMarshallV0Hero.entity.patch.json
content/DIF/chunk9/Miami/RaceMarshallv4HeadFix.entity.patch.json

Overriding the color of 47's jumpsuit as v0 is no longer necessary
47-as-Marshall v4 lost his head in the latest patch for some reason, so I've made another patch to add it back. This will likely be fixed soon, so it's not lumped in with the regular DIF v4 patch

feat: remove a now-redundant DIF fix for Miami and give 47 his head back when disguised as Marshall v4

---

content/SmallFixes/chunk6/SplitterSubtitleFixes/006112688578C526.dlge.json

In #267 I fixed many errors in the subtitles for The Splitter. I *intended* to fix one where "n'est-ce pas" was written as "ne's pa", but apparently I mistakenly included an unmodified version of the `dlge.json`. This will correct that error, and the subtitle.
May Ne's pa rest in peace. I hope Ne's ma is doing well in these difficult times.

fix: correct a mistakenly unmodified subtitle in a previous fix for The Splitter

---

content/SmallFixes/chunk25/MarrakeshCablesFix/location.entity.patch.json

Moves the cables located under the floor of the security room to be placed on top of the ground instead, moves a cable behind the camera box and fixes the cable pool in the server room previously clipping in the ground (+ add collision box to prevent climbing on top)

feat: fix various cables in the consulate security room

---

content/SmallFixes/chunk25/ConsulateGuardActFix/npc_mission_spider.entity.patch.json

Moves the end point of the act so that it doesn't clip into the level geometry (located in the upstairs consulate offices)

feat: fix consulate guard act clipping in level geometry

---

content/REPO/chunk0/ShurikenMeleeFix.repository.json

Fixes #364 by switching the order of the REPO items. Does not fully remove the deprecated thrown weapon tag just in case it's used somewhere.

feat: fix Bat Shuriken and some other shurikens to count as lethal melee for the purposes of some escalation conditions

---

content/SmallFixes/chunk18/DLGE/00C101A197C48E7A.dlge.json
content/SmallFixes/chunk23/DLGE/002E1193DC4D51C1.dlge.json

The first conversation reads "[...] ritual you **perfomed** on him last week.". This has been changed to "performed"
The second says "Nobody's better at making people disappear than the Delgado's." which has been changed to "Delgados" since it isn't possessive.

feat: fix typo in subtitles for `dr23640_hallowedground_shaman47sicarioacknowledge3` and `dr8061_parvatitalkstarget`

---

content/SmallFixes/chunk1/SgailBerserkGuardsFix/SgailBerserkGuardsFix.entity.patch.json

Without patch:
https://github.com/user-attachments/assets/36561dc3-0dff-439f-90ff-1e84b9065878
With patch:
https://github.com/user-attachments/assets/040e9bc9-358f-4262-ad70-62235d505c4f

feat: stop Elite Guards in Isle of Sgàil from opening fire on 47 immediately rather than going into the follow-warn state

---

manifest.json

In an unmodded game, the Intel for the Internal Haven Report found in the underground server farm just reads:
> This is an internal report showing the progress of the previous month's activity within the key expertise areas of Haven.
The item's description when selected in the Inventory tab (next to the Map) instead has the extended and much more relevant description:
> This is an internal report showing the progress of the previous month's activity within the key expertise areas of Haven. It notes several full identity wipes – or 'nulls', as they are called – having been completed and three additional ones have been reported as initiated just a few days ago. Presumably these belong to the Providence Partners. From the looks of it, Haven has its hooks into every major social and …

feat: correct unfinished description for Internal Haven Report

---

manifest.json

Currently the key used is `it`, which will have no effect as SMF simply ignores localisation keys it doesn't recognise.

fix: correctly apply Italian localisation for some disguises

---

.gitignore
content/SmallFixes/chunk27/FrenchMartini/0060A4156C155273.dlge.json
manifest.json

During the FrenchMartini ET there is a typo in 47's dialogue when talking to the dealer. He says:
> You need to understand. Le Chiffre HAS to loose tonight.
Fixes #453.
This PR updates the dialogue by changing it to:
> You need to understand. Le Chiffre HAS to lose tonight.

feat: fix 47's dialogue typo on FrenchMartini

---

content/SmallFixes/chunk26/ExitSignFix/sign_exit_a_00.entity.patch.json

Fixes #461
Move exit sign to the room it is parented to
unsure of the original idea behind it, but I moved and rotated the sign to face the door

feat: fix location of exit sign

---

content/SmallFixes/chunk16/AtlantideBannerRotation/atlantide_banner_a_01.entity.patch.json

Fixes #458
- rotates the banner on Galen Vholes' front porch by 180° so the metal bars are facing toward his house

feat: rotate an Atlantide banner to face the street

---

manifest.json

Original: 
> For the Hitman who dares to be bold. This beautiful purple fibre wire set will give your execution that certain \"Che nes cet quoi”. The only downside? Your victems will never know they went down in style.
Changed: 
> For the hitman who dares to be bold. This beautiful purple fiber wire set will give your execution that certain \"Je ne sais quoi\". The only downside? Your victims will never know they went down in style.
This makes the following changes:
- "Hitman" is now lowercase as it isn't a proper noun.
- "Fibre wire" has been changed to "fiber wire" to align with the item's name, and the spelling used for other fiber wires in the past
- The meaningless "French" text of "Che nes cet quoi" has been changed to "Je ne sais quoi" which actually means something
- "Victems" has …

feat: correct description for the Purple Streak Fiber Wire

---

content/SmallFixes/chunk20/NewZealandGrateAlignmentFix/Setpiece_NewZea_Grate_Ledge.entity.patch.json

Before:
after:
(sorry about the different angles)

feat: fixes the alignment of the ventilation grate hatch in hawke's bay
