- manifest.json
> feat: fix typo in Whittleton Creek map

- content/chunk0/Futo suit AI reactions.entity.patch.json
Sets the category to Ninja instead of Fallback
> feat: fix Futo Suit outfit AI reactions

- content/chunk6/00012C8A6C13B97F.dlge.json
> feat: fix Jeremy Bolt voice line being heard from anywhere

- manifest.json
> feat: fix name of A Rare Scoop feat

- manifest.json
Backported fixes from The Great Big Localisation Revamp. I have avoided custom descriptions as best I can.
Medicine Pills should be Allergy Pills, and linebreak fixes galore!
Thanks to IWILLCRAFT also for the translations provided.
> Backported TGBLR fixes

- manifest.json
new description for the description
> new description for the description

- content/chunk0/globaldata.entity.patch.json
> feat: Correct OutfitAICategory for Terminus Suit

- content/chunk24/CHAR_Bangkok_Civilian_Hotel_Guest_M_using_civfem04_fix.entity.patch.json
feat: Fixes female AI voice set being used (eAVV_CIVFEM04) for a specific male NPC in The Source (Zika). Replaced with eAVV_CIVMALE03 (Hello Yuri!)
> feat: Fix female AI voicelines for a specific NPC in The Source (Zika)

- content/chunk29/mission_vanilla.entity.patch.json
feat: Fixes various small LOD's (Level of Detail) models not appearing on suits when in the safehouse. [See here](https://www.youtube.com/watch?v=DClC6rng5G0).
Fixes #49
> Freelancer mirror LOD fixes

- content/chunk0/OUTFIT_Agent47_Hotsummer19_HeroA_v0.entity.patch.json
feat: Fix sunglasses being in 47's eyebrows on the Summer Suave Suit.
fixes #53
> feat: Fix sunglasses being in 47's eyebrows on the Summer Suave Suit.

- content/chunk29/mission_vanilla.entity.patch.json
This prevented even applying the mod at all
> fix: Fix setting property value that doesn't exist in mission_vanilla

- .github/workflows/release.yml
Thanks to grappigegovert for reminding me about **
> ci: exclude source files in subdirectories from releases

- content/chunk28/MissionStoryVoiceFix/0081FCBCB0158AEE.dlge.json
> feat: fix soundtag for crestruincheckin

- content/ElusiveVoices/chunk15/elusive_goldendoublet.entity.patch.json
- content/ElusiveVoices/chunk15/elusive_skittlebomb.entity.patch.json
- content/ElusiveVoices/chunk16/elusive_alabamaslammer.entity.patch.json
- content/ElusiveVoices/chunk16/scenario_gartersnake.entity.patch.json
- content/ElusiveVoices/chunk17/scenario_kingcobra.entity.patch.json
- content/ElusiveVoices/chunk18/scenario_anaconda.entity.patch.json
- content/ElusiveVoices/chunk20/elusive_adonis.entity.patch.json
- content/ElusiveVoices/chunk22/mission_flu.entity.patch.json
- content/ElusiveVoices/chunk3/elusive_vesper.entity.patch.json
- content/ElusiveVoices/chunk4/elusive_radler.entity.patch.json
- content/ElusiveVoices/chunk5/elusive_jockeyclub.entity.patch.json
- manifest.json
Fixes #76 
This affects the following targets:
- Owen Cage
- Klaus Liebleid
- Dame Barbara Elizabeth Keating
- Blair Reddington
- Basil Carnaby
- The Censor
- Galen Vholes
- Miranda Jamison
- Jimmy Chen
- Joanne Bayswater
- Terrence Chesterfield
- Jack Roe
- Robert Burk
> feat: change certain Elusive, Special Assignment, and Patient Zero voices to match their scripted dialogue

- content/SapienzaChurch/chunk26/Church_Windows_Long_B_00.entity.patch.json
- manifest.json
Fix by @Notexe
Fixes longstanding issue since HITMAN 2 (2018) that broke the visibility of the Sapienza church windows.
> feat: fix sapienza church windows

- content/SmallFixes/chunk25/ConsulateWindow/consulate_window_collision_a.entity.patch.json
- content/SmallFixes/chunk25/ConsulateWindow/consulate_window_collision_b.entity.patch.json
- manifest.json
Bullet decals will appear when it's shot, and gameplay won't be affected since the window already functions as it should besides that.
Made by Cybore on Discord, this will also add them to the Authors list.
> feat: restore collision to Swedish Consulate windows

- content/SmallFixes/chunk0/OutfitFilterKeywordReceiver/Dialogue_OutfitFilterKeywordReceiver_NPC.entity.patch.json
Fixes the Dialogue_OutfitFilterKeywordReceiver_NPC template so the muffle filter gets applied
> feat: fix muffle filter not being applied

- content/SmallFixes/chunk27/Gossip_NovikovSato/0002D4676470E54A.dlge.json
- content/SmallFixes/chunk27/Gossip_NovikovSato/0065D183BCD50B29.dlge.json
Every line of dialogue in this conversation had a different soundtag. Now they're all In-world_Mission_Normal, as they should be.
> feat: change incorrect soundtags for Gossip_NovikovSato

- content/SmallFixes/chunk25/ConsulateDrinkingActFix/coffeeglassfix.entity.patch.json
- content/SmallFixes/chunk26/LandslideDrinkingActFix/wineglassfix.entity.patch.json
- manifest.json
As title. See relevant discussion in the Discord channel.
> feat: fix some drinking acts in Landside and A Gilded Cage

- content/SmallFixes/chunk0/PhoneFixes/explosivephone_loopfix_v2.entity.patch.json
- content/SmallFixes/chunk0/PhoneFixes/flashphone_loopfix_v2.entity.patch.json
- content/SmallFixes/chunk12/GhostRobbersCantLockDoors/bathroomlock.entity.patch.json
- content/SmallFixes/chunk18/SubSuspicionFix/colombia_sub.entity.patch.json
- content/SmallFixes/chunk19/SugarEndsRace/sugar.entity.patch.json
One more Cybore fix that I forgot: ghosts can't lock doors.
> feat: New York bathroom door no longer locks if the robbers are dead/unconscious

- content/SmallFixes/chunk28/GreyOutfitFix/OUTFIT_Nightmare_LucasGrey_M_Actor_v0.entity.json
- content/SmallFixes/chunk28/GreyOutfitFix/replace lucas outfit.entity.patch.json
it is no longer wounded
Closes #122
> feat: fix Lucas Grey's outfit in Ambrose Island

- content/SmallFixes/chunk28/GreyOutfitFix/OUTFIT_Nightmare_LucasGrey_M_Actor_v0.entity.json
- content/SmallFixes/chunk28/GreyOutfitFix/replace lucas outfit.entity.patch.json
> fix: replace invalid RuntimeIDs introduced by 34135e3

- content/SmallFixes/chunk0/PonchoAnkleFix/PonchoNoReflex.entity.patch.json
> feat: remove unfinished "Mesh_Reflex" from the Makeshift Poncho Suit

- content/OACFixes/chunk0/globaldata.entity.patch.json
> feat: fix foley/AI reactions for Plague Doctor and foley for Superfan

- content/SmallFixes/chunk0/PenicillinCaneSound/penicillin_cane_sound_fix.entity.patch.json
> feat: fix penicillin cane sound

- content/NoDubaiSnipers/chunk0/outfits_gecko.entity.patch.json
- manifest.json
Toggleable in the options menu, enabled by default.
> feat: makes Snipers illegal to carry for Dubai guards (optional)

- content/SmallFixes/chunk0/InterpolBadge/itemart_interpol_badge_a.entity.patch.json
> feat: fix interpol badge rotation

- manifest.json
spelling of Meadow Brown Lounge
spacing of Explosive Snow Globe
capitalization of Beak Staff and Xmas Star
> feat: correct assorted typos

- content/SmallFixes/chunk27/Move Cake/Cakemove.entity.patch.json
Commit results
https://github.com/NeetBux-Hash/Tumbler.CakeRelocate/commit/f58952bfcfc938318a653bfe353e9b1490df022f
> feat: moved the cake slightly for intel safe scanning to work

- README.md
- manifest.json
As title; bumps the version to 1.0.0 and standardises the mod name to the one on [Nexus](https://www.nexusmods.com/hitman3/mods/784).
> feat!: standardise mod name to Unofficial Community Patch

- content/SmallFixes/chunk18/LaundryCartsFix/laundry_carts.entity.patch.json
- content/SmallFixes/chunk6/DumpsterFix/paris_notext_dumpster.entity.patch.json
This fixes the dumpster that has french text on Chongqing and the GAMA branded laundry carts on Santa Fortuna.
this fixes #79
> feat: fix dumpster and laundry carts

- content/SmallFixes/chunk6/FlightcaseSwap/scenario_rat.entity.patch.json
Changes a flightcase in Hush's building to one without a "The Class" sticker
> feat: swap flightcase in Hush's building

- content/SmallFixes/chunk27/BasementLockerLamps/location.entity.patch.json
Moved two lamps in the basement's locker room slightly down so that their ambient sound becomes audible
> feat: move two lamps to make sounds audible

- content/SmallFixes/chunk5/ActorSwapping/scenario_llama.entity.patch.json
- content/SmallFixes/chunk6/ActorSwapping/scenario_rat.entity.patch.json
Swap the voices of two actors in Mendoza's kitchen and two in Chongqing's landromat to make the voices used in their dialogue match how they look
> feat: swap voices to make dialogues match appearance

- content/SmallFixes/chunk26/FloatingKeycardReaderFix/floating_keycard_reader_fix.entity.patch.json
> feat: floating keycard reader on the side entrance to the villa has now been fixed

- content/SmallFixes/chunk0/PowerCabinetFix/power_cabinet_a_dark.entity.patch.json
- content/SmallFixes/chunk1/PowerCabinetFix/power_cabinet_a.entity.patch.json
- content/SmallFixes/chunk22/FloodlightFix/location.entity.patch.json
Fixed the sticker on the power cabinet being inside of the model,
copied the coordinates of the sound cue to match how it was in 2016 (in case it makes it more audible)
and fixed the material override applying to the wrong parts of the model + turned off the floodlight in the garage
> feat: fix power cabinets and floodlight

- content/SmallFixes/chunk28/chunk28/SpotlightFakelightFix/scenario_dugong.entity.patch.json
Fixes #88 and makes one spotlight turn on by default + add fakelight to it
> feat: fix fakelights not turning off with generator

- content/SmallFixes/chunk25/ShishaBarSinkFix/cafe_shisha_bar_a_00.entity.patch.json
reparented one FX so that it is no longer floating in the air and moved the overflowing water FX slightly so that the 2D plane is not sitting on the bar or clipping through it (room for improvement)
> feat: fix overflowing sink FX placements

- content/SmallFixes/chunk6/SplitterSubtitleFixes/00004847F46DFA09.dlge.json
- content/SmallFixes/chunk6/SplitterSubtitleFixes/0002BA25658C359E.dlge.json
- content/SmallFixes/chunk6/SplitterSubtitleFixes/001AFCBD657F3236.dlge.json
- content/SmallFixes/chunk6/SplitterSubtitleFixes/002B909367528050.dlge.json
- content/SmallFixes/chunk6/SplitterSubtitleFixes/002BC34CF58410E5.dlge.json
- content/SmallFixes/chunk6/SplitterSubtitleFixes/003ABC4A4AEA2384.dlge.json
- content/SmallFixes/chunk6/SplitterSubtitleFixes/004484D6CA868748.dlge.json
- content/SmallFixes/chunk6/SplitterSubtitleFixes/0046BFC7E3C39943.dlge.json
- content/SmallFixes/chunk6/SplitterSubtitleFixes/0051E1103831A27C.dlge.json
- content/SmallFixes/chunk6/SplitterSubtitleFixes/006112688578C526.dlge.json
- content/SmallFixes/chunk6/SplitterSubtitleFixes/0067625A37B0F314.dlge.json
- content/SmallFixes/chunk6/SplitterSubtitleFixes/00A7A40E0DC766CE.dlge.json
- content/SmallFixes/chunk6/SplitterSubtitleFixes/00B5689B984C467C.dlge.json
- content/SmallFixes/chunk6/SplitterSubtitleFixes/00B817B4C3A08F18.dlge.json
- content/SmallFixes/chunk6/SplitterSubtitleFixes/00E3131D95A1C96C.dlge.json
- content/SmallFixes/chunk6/SplitterSubtitleFixes/00EE15A2DCCCAA13.dlge.json
- content/SmallFixes/chunk6/SplitterSubtitleFixes/00FFBC0267B57004.dlge.json
- content/SmallFixes/chunk6/SplitterSubtitleFixes/ambsitationguards/00261B0942F83430.dlge.json
- content/SmallFixes/chunk6/SplitterSubtitleFixes/ambsitationguards/00402AC90036BAB6.dlge.json
- content/SmallFixes/chunk6/SplitterSubtitleFixes/ambsitationguards/0050E45F580461C6.dlge.json
- content/SmallFixes/chunk6/SplitterSubtitleFixes/ambsitationguards/00667BB95183A77C.dlge.json
- content/SmallFixes/chunk6/SplitterSubtitleFixes/ambsitationguards/0066B73160C4C28B.dlge.json
- content/SmallFixes/chunk6/SplitterSubtitleFixes/ambsitationguards/007C67C392D55218.dlge.json
- content/SmallFixes/chunk6/SplitterSubtitleFixes/ambsitationguards/00A52CCF3759D3FE.dlge.json
- content/SmallFixes/chunk6/SplitterSubtitleFixes/ambsitationguards/00AF034291920EB8.dlge.json
- content/SmallFixes/chunk6/SplitterSubtitleFixes/ambsitationguards/00B4A563BD6FFA95.dlge.json
- content/SmallFixes/chunk6/SplitterSubtitleFixes/ambsitationguards/00C552AE14D73466.dlge.json
- content/SmallFixes/chunk6/SplitterSubtitleFixes/ambsitationguards/00CF19EA342B5270.dlge.json
The Splitter has a lot of typos in its subtitles. This fixes all of them (I hope!)
> feat: fix a variety of subtitles in The Splitter

- content/DIF/chunk22/Cybore-HatTrick.entity.patch.json
By Cybore, submitted on Discord. Confirmed working by me.
> fix: 47 is no longer hatless when starting as a Handyman in Hokkaido

- content/SmallFixes/chunk24/TypoFixesBangkok/00BC3D917B60D1AB.dlge.json
"I don't know, would you wanna do nothin' all your **lfe**?" changed to "I don't know, would you wanna do nothin' all your life?"
> feat: correct a typo in crewtalkcrossfamily

- content/SmallFixes/chunk4/CantCloseDoorFix/manual_close_door_fix.entity.patch.json
> feat: fix a door in Berlin that can be manually opened, but not closed (#297)

- content/SmallFixes/chunk24/BugmanConversation/fix_hotel_manager_erroneously_talking_first.entity.patch.json
> feat: fix hotel manager erroneously talking first in the Bugman conversation

- content/SmallFixes/chunk0/DurianSmokeAndDamage/durian_smoke_green_with_no_damage.entity.patch.json
> feat: fix Durian smoke to be green with no damage to hero

- content/SmallFixes/chunk6/LambicGuardsGas/fix_lambic_guards_dying_to_gas.entity.patch.json
> feat: fix 47 disguised as a Facility Guard dying to gas in The Splitter

- content/SmallFixes/chunk10/OxygenTankFix/fix_ephemeral_oxygen_tank.entity.patch.json
> feat: fix disappearing oxygen tank

- content/SmallFixes/chunk19/BannerFix/remove_badly_placed_banner.entity.patch.json
> feat: remove badly placed banner in Miami on the expo building

- content/SmallFixes/chunk0/BlackboardMenuFix/blackboard_menu_italy_a.material.json
- content/SmallFixes/chunk25/BlackboardMenuFix/fix_blackboard_text.entity.patch.json
- content/SmallFixes/chunk26/BlackboardMenuFix/fix_double_text_on_blackboard.entity.patch.json
> feat: fix blackboards with overlayed text

- content/SmallFixes/chunk18/mini_ninja_toys/mini_ninjas_toys_activated.entity.patch.json
> feat: enable mini ninja figurines in Santa Fortuna

- content/SmallFixes/chunk15/BulletproofDoorsFix/sgail_wooden_doors_1.entity.patch.json
- content/SmallFixes/chunk15/BulletproofDoorsFix/sgail_wooden_doors_2.entity.patch.json
- original patch by Cybore
- apply patch to more doors by VoodooHillbilly
> feat: more wooden doors in Sgail can be shot/blown open (fixes #335)

- content/SmallFixes/chunk26/OldTownGateOpenAndShut/IronGate_Medieval_A_SizeC_manual.entity.patch.json
- the iron gate can now be manually closed after opening it
- the iron gate can now be opened and closed in World of Tomorrow
> feat: make Sapienza's Old Town gate more functional

- content/SmallFixes/chunk23/perimeter_guards_avoid_grass.entity.patch.json
feat: guards no longer enter stealth grass outside the barn unless provoked or distracted.
should close #357
> feat: guards no longer enter stealth grass outside the barn unless provoked or disatracted.

- content/SmallFixes/chunk15/SoundtagsAndSubtitles/004759CDA472EE9C.dlge.json
Was "This should make a find addition to the Ark Legacy."
Is now "This should make a fine addition to the Ark Legacy."
For some reason he does say "Ark Legacy" rather than "Ark **of** Legacy" so that stays.
> feat: correct typo in subtitles for `dr29058_oppnecklace_blakecompliment_nathaniel_002`

- content/SmallFixes/chunk29/SafehouseLadder/ladderhatch.entity.patch.json
> feat: fix void in safehouse maintenance ladder

- content/SmallFixes/chunk3/ZacharyBalconyLean/fix_zachary_balcony_lean.entity.patch.json
> feat: fix 47 clipping into Zachary's balcony when leaning on it

- content/SmallFixes/chunk16/SolitaireMarcyIrkVapeFix/SolitaireMarcyIrkVapeFix.entity.patch.json
Fixes #392 
This one had always *Irked* me, so it's good to have it fixed :]
> feat: stop a custom Freelancer target, Marcy Irk, from vaping forever

- content/SmallFixes/chunk25/StrandbergFilesFix/npc_mission_spider.entity.patch.json
Moves the files from the safe in Strandberg's office back into the safe (normally located far away in the market area)
> feat: fixes location of files inside Strandberg's safe

- content/FractureLiquidColor/chunk0/martinib.entity.patch.json
- content/FractureLiquidColor/chunk3/dartgarden_lemonjuice.entity.patch.json
Fixes #345 
Also fixes the same issue with the lemonade on Dartmoor garden show.
> feat: fixes liquid color on martinis and Dartmoor garden lemon juice cups.

- content/SmallFixes/chunk1/EyelashesMaterialFix/00FDD9DA7B2801A2.material.json
Fixes the material not displaying the transparency of the eyelashes properly, resulting in fully black eyelashes
> feat: fixes eyelashes alpha not working

- content/SmallFixes/chunk1/SuitcaseMaterialFix/suitcase_box_a.material.json
Fixed the suitcase/chest material so that it does not appear weirdly white (may need to check for collateral)
Before:
After:
> feat: fixed suitcase material using wrong values

- content/SmallFixes/chunk29/CuttingBoardLocationFix/Setpiece_Evergreen_Cut_Fish.entity.patch.json
> feat: repositions the cutting board, therefore fixing its clipping

- content/SmallFixes/chunk0/FloatingDubaiLamps/modern_shell_lamp_a.entity.patch.json
Fixes #460
Fixed the positions of a few lamps in the staircase leading to the penthouse so that they do not appear detached from the wall
> feat: fixed position of lamps in dubai staircase

- content/REPO/chunk0/NPC-Tweaks.repository.json
Change Garry Lunn to Gary Lunn, as it was in Hitman (2016)
> feat: change garry lunn to gary lunn

- content/SmallFixes/chunk24/BaijuContestantHair/BaijuContestantHair.entity.patch.json
Before:
(picture by Dribbleondo)
After:
> feat: change hair on Infiltrator contestant (Kaylee Edwards) who was wrongly using the "hat" version of her hair
